---
- name: Add ec2-user to the docker group and reboot server
  hosts: aws
  become: yes  # Run tasks with root privileges

  tasks:
    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Reboot the server
      reboot:
        reboot_timeout: 300
        test_command: uptime

    - name: Wait for the server to come back after reboot
      wait_for_connection:
        delay: 30
        timeout: 360


