---
- name: Install MySQL on Amazon Linux
  hosts: aws
  become: yes  # Run tasks with root privileges
  tasks:
    - name: Check if MySQL is installed
      command: "mysql --version"
      ignore_errors: yes  # Ignore errors if MySQL is not installed
      register: mysql_check

    - name: Install MySQL if not installed
      yum:
        name: mysql-server
        state: present
      when: mysql_check.rc != 0  # Only install if MySQL is not found

    - name: Start MySQL service
      service:
        name: mysqld
        state: started
      when: mysql_check.rc != 0  # Only start if MySQL is not found

    - name: Enable MySQL service on boot
      service:
        name: mysqld
        enabled: yes
      when: mysql_check.rc != 0  # Only enable if MySQL is not found
