---
- name: Install MySQL on Amazon Linux 2
  hosts: aws
  become: yes  # Run tasks with root privileges
  tasks:
    - name: Install MySQL
      ansible.builtin.command: yum install -y mariadb-server
      ignore_errors: yes  # Ignore errors if MySQL is already installed
      register: mysql_install_result

    - name: Start MySQL service
      ansible.builtin.command: systemctl start mariadb
      ignore_errors: yes  # Ignore errors if the service is already running

    - name: Enable MySQL service on boot
      ansible.builtin.command: systemctl enable mariadb
