---
- name: Install Git and Docker, and start Docker
  hosts: aws
  become: yes

  tasks:
    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install Docker dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
