---
- name: Install Java, Git, and Docker on Amazon Linux
  hosts: aws
  become: yes

  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest

    - name: Install Java JDK 11
      yum:
        name: java-11-amazon-corretto-devel
        state: present

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
