---
- name: Ensure Specific Ports are Open
  hosts: aws
  become: yes
  gather_facts: yes

  tasks:
    - name: Install iptables
      ansible.builtin.package:
        name: iptables
        state: present
      when: ansible_distribution == "Amazon"  # Check for Amazon Linux 2 distribution

    - name: Ensure Port 80 is Open
      ansible.builtin.shell: iptables -A INPUT -p tcp --dport 80 -j ACCEPT
      when: ansible_distribution == "Amazon"  # Check for Amazon Linux 2 distribution

    - name: Ensure Port 443 is Open
      ansible.builtin.shell: iptables -A INPUT -p tcp --dport 443 -j ACCEPT
      when: ansible_distribution == "Amazon"  # Check for Amazon Linux 2 distribution

    - name: Ensure Port 8080 is Open
      ansible.builtin.shell: iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
      when: ansible_distribution == "Amazon"  # Check for Amazon Linux 2 distribution
